/**
 * App Redux Action Types
 */

// Auth Actions
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_FAILURE = 'LOGOUT_USER_SUCCESS_FAILURE';
export const CHECK_AUTH_STATUS = 'CHECK_AUTH_STATUS';
export const CHECK_AUTH_STATUS_SUCCESS = 'CHECK_AUTH_STATUS_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const FORGOT_PAASWORD = 'FORGOT_PAASWORD';
export const FORGOT_PAASWORD_SUCCESS = 'FORGOT_PAASWORD_SUCCESS';
export const FORGOT_PAASWORD_FAILURE = 'FORGOT_PAASWORD_SUCCESS_FAILURE';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILURE = 'CHANGE_PASSWORD_SUCCESS_FAILURE';

//files action
export const GET_ALL_FILES = 'GET_ALL_FILES';
export const GET_ALL_FILES_SUCCESS = 'GET_ALL_FILES_SUCCESS';
export const GET_ALL_FILES_FAILURE = 'GET_ALL_FILES_FAILURE';

export const DOWNLOAD_FILE = 'DOWNLOAD_FILE';
export const DOWNLOAD_FILE_SUCCESS = 'DOWNLOAD_FILE_SUCCESS';
export const DOWNLOAD_FILE_FAILURE = 'DOWNLOAD_FILE_FAILURE';

//notification actions
export const NOTIFICATION = 'NOTIFICATION';
export const NOTIFICATION_FAILURE = 'NOTIFICATION_FAILURE';
export const NOTIFICATION_SUCCESS = 'NOTIFICATION_SUCCESS';

//notification actions
export const SEEN_NOTIFICATION = 'SEEN_NOTIFICATION';
export const SEEN_NOTIFICATION_FAILURE = 'SEEN_NOTIFICATION_FAILURE';
export const SEEN_NOTIFICATION_SUCCESS = 'SEEN_NOTIFICATION_SUCCESS';

export const DELETE_NOTIFICATION = 'DELETE_NOTIFICATION';
export const DELETE_NOTIFICATION_FAILURE = 'DELETE_NOTIFICATION_FAILURE';
export const DELETE_NOTIFICATION_SUCCESS = 'DELETE_NOTIFICATION_SUCCESS';

//settings actions
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
export const GET_USER_SETTINGS = 'GET_USER_SETTINGS';
export const GET_USER_SETTINGS_SUCCESS = 'GET_USER_SETTINGS_SUCCESS';

//files action
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';