/**
 * App Redux Action Types
 */

// Auth Actions
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_FAILURE = 'LOGOUT_USER_SUCCESS_FAILURE';
export const CHECK_AUTH_STATUS = 'CHECK_AUTH_STATUS';
export const CHECK_AUTH_STATUS_SUCCESS = 'CHECK_AUTH_STATUS_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';

//files action
export const GET_ALL_FILES = 'GET_ALL_FILES';
export const GET_ALL_FILES_SUCCESS = 'GET_ALL_FILES_SUCCESS';
export const GET_ALL_FILES_FAILURE = 'GET_ALL_FILES_FAILURE';

export const DOWNLOAD_FILE = 'DOWNLOAD_FILE';
export const DOWNLOAD_FILE_SUCCESS = 'DOWNLOAD_FILE_SUCCESS';
export const DOWNLOAD_FILE_FAILURE = 'DOWNLOAD_FILE_FAILURE';

//settings actions
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
export const GET_USER_SETTINGS = 'GET_USER_SETTINGS';
export const GET_USER_SETTINGS_SUCCESS = 'GET_USER_SETTINGS_SUCCESS';

//files action
